# Default values for micro-customer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ibmcase/bluecompute-customer
  tag: latest
  pullPolicy: Always

service:
  name: customer
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

global:
  hs256key:
    secret:
    secretName:

  bluemix:
    apiKey:

    target:
      endpoint: api.ng.bluemix.net
      org:
      space:

    clusterName:

tags:
  bluemix: false
  localdb: false

hs256key:
  skipDelete: true
  secretName: hs256-key
  secret:

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

dataloader:
  image:
    repository: ibmcase/bluecompute-dataloader
    tag: latest

bash:
  image:
    repository: ibmcase/bluecompute-bash-curl-ssl
    tag: latest

couchdb:
  binding:
    name: binding-customer-couchdb
