apiVersion: batch/v1
kind: Job
metadata:
  name: {{ cat .Release.Name "-" .Chart.Name "-create-user-" (randAlphaNum 5 | lower) | nospace | trunc 63 }}
  labels:
    app: bluecompute
    micro: customer
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  template:
    metadata:
      name: {{ cat .Release.Name "-" .Chart.Name "-create-user-" (randAlphaNum 5 | lower) | nospace }}
      labels:
        app: bluecompute
        micro: customer
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
             "name": "bluecompute-customer-wait-for-customer-service",
             "image": "{{ .Values.bash.image.repository }}:{{ .Values.bash.image.tag }}",
             "imagePullPolicy": "IfNotPresent",
             "command": ["/bin/bash", "-c", "until curl --max-time 1 http://{{ .Release.Name }}-{{ .Values.service.name }}:{{ .Values.service.externalPort }}; do echo waiting for customer-service; sleep 1; done;"]
          }
        ]'
    spec:
      restartPolicy: Never
      containers:
      - name: create-user
        image: {{ .Values.bash.image.repository }}:{{ .Values.bash.image.tag }}
        command: ["/bin/bash", "-c" ]
        args:
        - >
            secret=`cat /var/run/secrets/hs256-key/key`;
            jwt1=`echo -n '{"alg":"HS256","typ":"JWT"}' | openssl enc -base64`;
            jwt2=`echo -n '{"scope":["admin"],"user_name":"admin"}' | openssl enc -base64`;
            jwt3=`echo -n "${jwt1}.${jwt2}" | tr '+\/' '-_' | tr -d '=' | tr -d '\r\n'`;
            jwt4=`echo -n "${jwt3}" | openssl dgst -binary -sha256 -hmac "${secret}" | openssl enc -base64 | tr '+\/' '-_' | tr -d '=' | tr -d '\r\n'`;
            jwt=`echo -n "${jwt3}.${jwt4}"`;
            for i in `seq 1 120`; do
              curl --max-time 5 -H "Content-type: application/json" -H "Authorization: Bearer ${jwt}" -X POST -d '{"username": "user", "password": "passw0rd", "firstName": "user", "lastName": "name", "email": "user@name.com"}' http://{{ .Release.Name }}-{{ .Values.service.name }}:{{ .Values.service.externalPort }}/micro/customer;
            done
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/run/secrets/hs256-key
          name: hs256-key
      volumes:
      - name: hs256-key
        secret:
          defaultMode: 420
          secretName: {{ template "hs256SecretName" . }}
