replicaCount: 1

image:
  repository: ibmcase/bluecompute-catalog
  pullPolicy: Always
  tag: latest

service:
  name: catalog
  type: ClusterIP
  externalPort: 8081
  internalPort: 8081

dataloader:
  image:
    repository: ibmcase/bluecompute-dataloader
    tag: latest

inventory:
  service:
    url:

elasticsearch:
  binding:
    name: binding-catalog-elasticsearch

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi
